name: SQL Yoga To-Do Example
version: 0.0.1
build: 1
encrypt stacks: false
multiple instances: false
relaunch in background: false
creator code:
application data folder:
  user:
    default:
    macos:
    windows:
    linux:
    ios:
    android:
  shared:
    default:
    macos:
    windows:
    linux:
preferences filename:
  user:
    default: SQL Yoga To Do Example.prefs
    macos: com.sqlyoga.todo-example.todo-osx
    windows:
    linux:
    ios:
    android:
  shared:
    default:
    macos:
    windows:
    linux:
ui:
  - folder: ./ui
templates:
  - folder: ./templates
libraries:
  - folder: ./libraries
frontscripts:
  - folder: ./frontscripts
backscripts:
  - folder: ./backscripts
helpers:
  - filename: "[[FRAMEWORK]]/helpers/preferences"
  - filename: "[[FRAMEWORK]]/helpers/window_manager"
  - folder: ./helpers
behaviors:
  - folder: ./behaviors

sql yoga:
  configuration:
    - filename: ./database
      database key: default

build folder: ../builds
build profiles:
  all profiles:
    packager callbacks stackfile:
    certificates:
      macos:
        name:
    copy files:
      all platforms:
        - filename: ./database/to-do.sqlite
      macos:
      windows:
      linux:
      ios:
      android:
  release:
  beta:
